== Conformance
This draft specification defines seven requirements/conformance classes for the Styles API building blocks:

* "core" provides access to styles and their metadata. JSON is a mandatory encoding in requests and responses where JSON schemas have been specified for the Styles API.
* "global styles" defines globally available styles at the root of the API (`/styles`).
* "collection styles" defines style available per collection as defined in OGC API - Common - Part 2  (`/collections/{collectionId}/styles`).
* "manage-styles" adds the capabilities for creating, updating and deleting styles.
* "style-validation" adds the capability to validate a stylesheet.

In addition, there are four requirements/conformance classes for style encodings supported by resources of the API:

* "mapbox-styles" supports Mapbox Styles as a style encoding.
* "sld-se" supports OGC SLD 1.0 and/or 1.1 as a style encoding.
* "csjson" supports OGC Cartographic Symbology JSON as a style encoding.
* "cscss" supports OGC Cartographic Symbology CSS as a style encoding.

The standardization target for all classes is: Web API.

Conformance with this draft specification shall be checked using all the relevant tests specified in Annex A (normative) of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures
and the OGC Compliance Testing web site.

In order to conform to this draft specification, a software implementation has to implement "core".
