[[rc_core]]
== Requirements Class "Core"

include::requirements/requirements_class_core.adoc[]

[[ogcapi-common-core]]
=== OGC API - Common - Part 1: Core

https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1: Core] is an approved OGC standard defining common requirements for OGC APIs.
The "Core" requirements class of that standard is a dependency of this OGC API - Styles standard.
Additionally, implementations are strongly recommended to implement the https://docs.ogc.org/is/19-072/19-072.html#rc_landing-page-section["Landing Page" requirements class]
which defines requirements for the Landing Page, Conformance Declaration and API Definition resources.

[[base-resource]]
=== Base resource

[[req_core_base-resource-link]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/base-resource-link*
^|A |The content of any base resource (at path `{baseResource}`) with which styles are associated in the API SHALL include a link to a Styles resource at path `{baseResource}/styles` (link relation type 'http://www.opengis.net/def/rel/ogc/1.0/styles').
|===

[[example_lp]]
.Landing page in JSON
=================
For a general purpose Styles API the base resource will be the Landing Page of the API. The following is an example of a landing page with a Styles sub-resource. This implementation supports the "json" conformance class, but not the "html" conformance class.

[source,JSON]
----
{
  "links": [
    {
      "href": "https://example.org/api/v1",
      "rel": "self",
      "type": "application/json",
      "title": "this document"
    },
    {
      "href": "https://example.org/api/v1/api",
      "rel": "service-desc",
      "type": "application/vnd.oai.openapi+json;version=3.0",
      "title": "the API definition in OpenAPI JSON"
    },
    {
      "href": "https://example.org/api/v1/api.html",
      "rel": "service-doc",
      "type": "text/html",
      "title": "the API documentation in HTML"
    },
    {
      "href": "https://example.org/api/v1/conformance",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/conformance",
      "type": "application/json",
      "title": "list of conformance classes implemented by this API"
    },
    {
      "href": "https://example.org/api/v1/styles",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/styles",
      "type": "application/json",
      "title": "the styles shared via this API"
    }
  ]
}
----
=================

[[conformance_declaration]]
=== Declaration of conformance classes

The following is an example of the conformance declaration of an API that implements all requirements classes of this standard and OGC API Common Core, except "html".

[[example_cc]]
.Conformance declaration in JSON
=================
[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/json",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/oas30",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/manage-styles",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/style-validation",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/resources",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/manage-resources",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/mapbox-styles",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/sld-10",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/sld-11"
  ]
}
----
=================

[[get_styles]]
=== Fetch styles

This operation returns a list of styles that are currently available for the base resource.

A description of each style can be included in each element of this list, as detailed in the <<uml-model>>.

[[req_core_styles-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/styles-op*
^|A |The server SHALL support the HTTP GET operation at the path `{baseResource}/styles`.
|===

[[req_core_styles-success]]
[width="90%",cols="2,6a",separator="!"]
!===
^!*Requirement {counter:req-id}* !*/req/core/styles-success*
^!A !A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^!B a!The content of that response SHALL be based upon the https://github.com/opengeospatial/ogcapi-styles/blob/master/standard/openapi/schemas/styles-core/styles.yaml[styles.yaml OpenAPI 3.0 schema]:

.styles.yaml
[source,yaml]
----
include::openapi/schemas/styles-core/styles.yaml[]
----

.styleDescription.yaml
[source,YAML]
----
include::openapi/schemas/styles-core/styleDescription.yaml[]
----

^!C !The `styles` member SHALL include one item for each style currently on the server.
^!D !The `id` member of each style SHALL be unique.
^!E !Each style SHALL have at least one link to a style encoding supported for the style (link relation type: `stylesheet`) with the `type` attribute stating the media type of the style encoding.
^!F !The `default` member SHALL, if provided, be the `id` of one of the styles in the `styles` array.
^!G !If one or more GeoDataClass is registered for the data for which the style is intended, a URI to each of these GeoDataClasses SHALL be included in the
`geoDataClasses` array of the corresponding element of the Styles resource.
The GeoDataClass definition would specify the logical schema for each feature type present within that GeoDataClass.
^!H !If a thumbnail is available for a style in the style metadata, a link with the link relation type `preview` SHALL be provided in the Styles resource.
!===

The metadata, including the links to the GeoDataClasses and previews, should also be embedded within the representation of the style, if that is supported by the style encoding.
Also including this metadata in the Styles resource provide clients access to this information without the need to send requests for each all style resource for discovering
a specific style of interest.

[[rec_core_style-title]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/style-title*
^|A |If a style has a title, it SHOULD be included in the `title` member of the style object.
|===

[[example_styles]]
.JSON encoding of styles
=================
[source,JSON]
----
{
  "default": "topographic",
  "styles": [
    {
      "id": "night",
      "title": "Topographic night style",
      "geoDataClasses": [ "https://registry.example.com/geodataclasses/tds-6.1" ],
      "links": [
        {
          "href": "https://example.com/api/v1/styles/night?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/night?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/resources/night-thumbnail.png",
          "type": "image/png",
          "rel": "preview"
        }
      ]
    },
    {
      "id": "topographic",
      "title": "Regular topographic style",
      "geoDataClasses": [ "https://registry.example.com/geodataclasses/tds-6.1" ],
      "links": [
        {
          "href": "https://example.com/api/v1/styles/topographic?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/topographic?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/resources/topographic-thumbnail.png",
          "type": "image/png",
          "rel": "preview"
        }
      ]
    }
  ]
}
----
=================

[[get_style]]
=== Fetch style

This operation returns the stylesheet of a style.

[[req_core_style-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-op*
^|A |The server SHALL support the HTTP GET operation at the path `{baseResource}/styles/{styleId}` for each style referenced from the Styles resource at `{baseResource}/styles`.
|===

[[req_core_style-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL conform to the media type stated in the `Content-Type` header.
^|C |The language used in linguistic text in the response SHALL be consistent with the language stated in the `Content-Language` header.
|===

[[req_core_style-feature-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-feature-type*
^|A a|The feature type identifiers qualifying a styling rule in the style sheet response SHALL resolve to the data in an OGC API collection by matching in this strict order of priority:

1. An explicit feature type name identified at the individual feature level such as
data layers in multi-layer vector tiles (e.g., layer `name` in https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers[Mapbox Vector Tiles]),
https://docs.ogc.org/is/21-045r1/21-045r1.html#feature-types[JSON-FG],
or a schema https://docs.ogc.org/is/23-058r2/23-058r2.html#_type[role].
2. The single feature type identifier listed in the `featureTypes` array of the collection description.
3. The `{collectionId}` of the collection resource itself.
|===
