////
TODO: move normative statements to separate files
////

[[styles-api]]
== API building blocks for styles

=== Base resources

Styles can be associated with a variety of resources in an API, for example, a feature dataset, a feature collection, or a coverage. This standard does not restrict the resource types with which styles may be associated.

This standard uses the term "base resource" for such resources. In the API, styles are sub-resources of a base resource.

Typical base resources are:

* The API landing page at path `/`.
** If the API provides distributions of a dataset, then the styles will be associated with the dataset.
** If the API does not provide access to data, it is a general purpose Styles API and the styles will typically be applicable to a range of data resources available elsewhere.
* A data collection at path `/collections/{collectionId}`.

=== Resources referenced from styles

Stylesheets often reference external resources, especially symbols and fonts to be used in the rendering process. Symbols are either managed as a single file for each symbol or they are organized in a sprite. In a sprite, all symbols are combined into a single bitmap image to reduce memory and the number of http requests. 

Since these resources are referenced from stylesheets using a URI of the resource, the details where and how the resources are hosted are not important and this specification does not specify API building blocks for publishing such resources.

=== Overview

The API building blocks support the resources and operations listed in the table below with the associated conformance class and the link to the document section that specifies the requirements.

The `{baseResource}` is a path template for any API resource with which styles can be associated.

[#tldr2,reftext='{table-caption} {counter:table-num}']
.Overview of resources and applicable HTTP methods
[cols="15,24,8,18,25",options="header"]
!===
|Resource |Path |HTTP method |Conformance class|Document reference
|Base resource |`{baseResource}` |GET |core |<<base-resource>>
|Conformance declaration |`/conformance` |GET |core |<<conformance_declaration>>
.3+|Styles .3+|`{baseResource}/styles` |GET |core |<<get_styles>>
.2+|POST |manage-styles |<<create_style>>
|style-validation |<<style_validate>>
.4+|Style .4+|`{baseResource}/styles/{styleId}` |GET |core |<<get_style>>
.2+|PUT |manage-styles |<<replace_style>>
|style-validation |<<style_validate>>
|DELETE |manage-styles |<<delete_style>>
.3+|Style metadata .3+|`{baseResource}/styles/{styleId}/metadata` |GET |core |<<get_style_metadata>>
|PUT |manage-styles |<<replace_style_metadata>>
|PATCH |manage-styles |<<update_style_metadata>>
!===

////
|Landing page |`/` |GET |core |<<landing_page>>
|Resources |`/resources` |GET |resources |<<get_resources>>
.3+|Resource .3+|``{baseResource}/resources/{resourceId}` |GET |resources |<<get_resource>>
|PUT |manage-resources |<<update_resource>>
|DELETE |manage-resources |<<delete_resource>>
////

This standard supports multiple style encodings (stylesheets) per style. For example, an API may publish a "night" style in the style encodings OGC SLD 1.0, OGC SLD 1.1 and Mapbox Style. The client will select the stylesheet that fits best based on its capabilities and preferences.

This standard only specifies Style Metadata as a sub-resource to a Style resource. APIs and other specification may specify additional sub-resources. For example, a Map sub-resource could be provided that returns map representations of the base resource rendered using the style.

[[rc_core]]
=== Requirements Class "Core"

include::requirements/requirements_class_core.adoc[]

[[ogcapi-common-core]]
==== OGC API - Common - Part 1: Core

At the time of writing, <<CommonCore,OGC API - Common - Part 1: Core>> is a candidate standard and not yet an approved standard. The requirements class "Core" has to be supported. This includes support for the API resources Landing Page, Conformance Declaration and API Definition.

[[base-resource]]
==== Base resource

[[req_core_base-resource-link]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/base-resource-link*
^|A |The content of any base resource (at path `{baseResource}`) with which styles are associated in the API SHALL include a link to a Styles resource at path `{baseResource}/styles` (link relation type 'http://www.opengis.net/def/rel/ogc/1.0/styles').
|===

[[example_lp]]
.Landing page in JSON
=================
For a general purpose Styles API the base resource will be the Landing Page of the API. The following is an example of a landing page with a Styles sub-resource. This implementation supports the "json" conformance class, but not the "html" conformance class.

[source,JSON]
----
{
  "links": [
    {
      "href": "https://example.org/api/v1",
      "rel": "self",
      "type": "application/json",
      "title": "this document"
    },
    {
      "href": "https://example.org/api/v1/api",
      "rel": "service-desc",
      "type": "application/vnd.oai.openapi+json;version=3.0",
      "title": "the API definition in OpenAPI JSON"
    },
    {
      "href": "https://example.org/api/v1/api.html",
      "rel": "service-doc",
      "type": "text/html",
      "title": "the API documentation in HTML"
    },
    {
      "href": "https://example.org/api/v1/conformance",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/conformance",
      "type": "application/json",
      "title": "list of conformance classes implemented by this API"
    },
    {
      "href": "https://example.org/api/v1/styles",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/styles",
      "type": "application/json",
      "title": "the styles shared via this API"
    }
  ]
}
----
=================

[[conformance_declaration]]
==== Declaration of conformance classes

The following is an example of the conformance declaration of an API that implements all requirements classes of this standard and OGC API Common Core, except "html".

[[example_cc]]
.Conformance declaration in JSON
=================
[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/json",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/oas30",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/manage-styles",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/style-validation",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/resources",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/manage-resources",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/mapbox-styles",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/sld-10",
    "http://www.opengis.net/spec/ogcapi-styles-1/1.0/conf/sld-11"
  ]
}
----
=================

[[get_styles]]
==== Fetch styles

This operation returns a list of styles that are currently available for the base resource.

[[req_core_styles-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/styles-op*
^|A |The server SHALL support the HTTP GET operation at the path `{baseResource}/styles`.
|===

[[req_core_styles-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/styles-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL be based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - styles
properties:
  styles:
    type: array
    items:
      type: object
      required:
        - id
        - links
      properties:
        id:
          type: string
        title:
          type: string
        links:
          type: array
          minItems: 1
          items:
            $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml'
  default:
    type: string
----
^|C |The `styles` member SHALL include one item for each style currently on the server.
^|D |The `id` member of each style SHALL be unique.
^|E |Each style SHALL have at least one link to a style encoding supported for the style (link relation type: `stylesheet`) with the `type` attribute stating the media type of the style encoding.
^|F |Each style SHALL have a link to the style metadata (link relation type: `describedby`) with the `type` attribute stating the media type of the metadata encoding.
^|G |The `default` member SHALL, if provided, be the `id` of one of the styles in the `styles` array.
|===

#TODO: Currently the links to the thumbnails of a style are available only as part of the style metadata (see <<rec_core_style-md-preview,recommendation "/rec/core/style-md-preview">>). To display an overview of the styles with a thumbnail image, a client needs to send multiple requests, the first one for the list of styles and then a request for each style metadata to get the thumbnail links. Whether the preview should also be included for each style in the Styles resource should be discussed.#

[[rec_core_style-title]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/style-title*
^|A |If a style has a title, it SHOULD be included in the `title` member of the style object.
|===

[[example_styles]]
.JSON encoding of styles
=================
[source,JSON]
----
{
  "default": "topographic", 
  "styles": [
    {
      "id": "night",
      "title": "Topographic night style",
      "links": [
        {
          "href": "https://example.com/api/v1/styles/night?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/night?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/night/metadata?f=json",
          "type": "application/json",
          "rel": "describedby"
        }
      ]
    },
    {
      "id": "topographic",
      "title": "Regular topographic style",
      "links": [
        {
          "href": "https://example.com/api/v1/styles/topographic?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/topographic?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/topographic/metadata?f=json",
          "type": "application/json",
          "rel": "describedby"
        }
      ]
    }
  ]
}
----
=================

[[get_style]]
==== Fetch style

This operation returns the stylesheet of a style.

[[req_core_style-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-op*
^|A |The server SHALL support the HTTP GET operation at the path `{baseResource}/styles/{styleId}` for each style referenced from the Styles resource at `{baseResource}/styles`.
|===

[[req_core_style-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL conform to the media type stated in the `Content-Type` header.
^|C |The language used in linguistic text in the response SHALL be consistent with the language stated in the `Content-Language` header.
|===

The `Content-Language` header in a HTTP response is used to describe the language(s) intended for the audience. If no Content-Language is specified, the default is that the content is intended for all language audiences.

[[get_style_metadata]]
==== Fetch style metadata

This operation returns the metadata of a style.

[[req_core_style-md-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-md-op*
^|A |The server SHALL support the HTTP GET operation at the path `{baseResource}/styles/{styleId}/metadata` for each style metadata referenced from the Styles resource at `{baseResource}/styles`.
|===

[[req_core_style-md-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/style-md-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL be based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - id
properties:
  id:
    type: string
    title: Style Identifier
    description: the identifier of the style
  title:
    type: string
    title: Title
    description: a title for the style, suitable for indicating the style usage in a style listing.
  description:
    type: string
    title: Description
    description: a longer description of the style, including all information needed to facilitate understanding, such as applicability, classification methods, reference to norms and whatever other information the user should be aware of before using the style
  keywords:
    type: array
    title: Keywords
    description: a list of well-known keywords that would help locating the style in a catalog
    items:
      type: string
  pointOfContact:
    type: string
    title: Point of Contact
    description: information that can be used to contact the authors or custodians for the style (free form, can be anything from an e-mail address to physical address and phone numbers)
  license:
    type: string
    title: License
    description: the license under which the style is made available
  created:
    type: string
    format: date-time
    title: Created
    description: the timestamp when the style was first produced
  updated:
    type: string
    format: date-time
    title: Updated
    description: the timestamp of the last style change/revision
  scope:
    type: string
    title: Scope
    description: the scope of this metadata record, fixed to "style"
    enum:
      - style
  version:
    type: string
    title: Version
    description: the version number for the current stylesheets of the style
  stylesheets:
    type: array
    title: Stylesheets
    description: the documents in different style encodings in which the style is available
    items:
      type: object
      required:
        - link
      properties:
        title:
          type: string
          title: Title
          description: the title of the encoding language, e.g. Mapbox Style, SLD, GeoCSS or CMSS
        version:
          type: string
          title: Version
          description: the version of the encoding language used, e.g., 1.0
        specification:
          type: string
          format: url
          title: Specification
          description: a link to the style encoding specification, e.g. https://docs.mapbox.com/mapbox-gl-js/style-spec/
        native:
          type: boolean
          title: Native
          description: true or false, indicating if this is the native encoding of the style, possibly hand prepared, or an on-the-fly conversion, with potential loss of details in the process
        link:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml'
  layers:
    type: array
    title: Data Layers
    description: the layers involved in the symbolization (which might be just one), and the attributes used by the style for each layer (could be none); while part of this information could be retrieved from the stylesheets themselves, this is a succinct representation enumerating the minimum set of data the style needs in order to actually symbolize data
    items:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          title: Identifier 
          description: a layer id, typically the same identifier used in the style to refer to the layer
        description:
          type: string
          title: Description
          description: a layer description, which can be used to understand the role of the layer in the style
        dataType:
          type: string
          title: Data Type
          description: the type of data represented in the layer
          enum:
            - vector
            - map
            - coverage
            - model
        geometryType:
          type: string
          title: Geometry Type
          description: the geometry type of the features shown in this layer, if dataType is "vector"
          enum:
            - points
            - lines
            - polygons
            - solids
            - any
        propertiesSchema:
          type: object
          title: Attributes
          description: the properties that the style needs in order to perform filtering, classification, symbolization
          additionalProperties:
            $ref: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json#/definitions/Schema'
        sampleData:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml'
  links:
    type: array
    title: Links
    description: links of the style metadata, including the "self" and "alternate" links
    items:
      $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml'
----
^|C |The language used in linguistic text in the response SHALL be consistent with the language stated in the `Content-Language` header.
|===

[[rec_core_style-md-sample-data]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/style-md-sample-data*
^|A |Sample data that can be used to illustrate the style SHOULD be represented as links with the following link relation types:

* `enclosure` for links to sample data that may be downloaded (e.g. a GeoPackage);
* `collection` for links to a Collection resource according to OGC API Common (e.g. `/collections/{collectionId}`; the collection may be available as features (tiled or not) or as gridded data);
* `start` for links to a Features resource according to OGC API Features (e.g. `/collections/{collectionId}/items`; the response may contain a `next` link to additional features);
* `http://www.opengis.net/def/rel/ogc/1.0/tiles` for a link to a Tile Sets resource (e.g. `/collections/{collectionId}/tiles`).
|===

#TODO: Add guidance for links to coverage data?#

[[rec_core_style-md-preview]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/core/style-md-preview*
^|A |A link to a thumbnail SHOULD be included with link relation `preview` (specified by RFC 6903) and the appropriate media type in the `type` parameter.
|===

The thumbnail may be an image that is published as a resource in the API. The thumbnail can reference an appropriate raster tile, a map request, etc.

[[example_style_metadata]]
.Style metadata in JSON
=================
[source,JSON]
----
{
  "id": "night",
  "title": "Topographic night style",
  "description": "This topographic basemap style is designed to be used in situations with low ambient light. The style supports datasets based on the TDS 6.1 specification.",
  "keywords": [
    "basemap",
    "TDS",
    "TDS 6.1",
    "OGC API"
  ],
  "pointOfContact": "John Doe",
  "accessConstraints": "unclassified",
  "dates": {
    "creation": "2019-01-01T10:05:00Z",
    "publication": "2019-01-01T11:05:00Z",
    "revision": "2019-02-01T11:05:00Z",
    "validTill": "2019-02-01T11:05:00Z",
    "receivedOn": "2019-02-01T11:05:00Z"
  },
  "scope": "style",
  "version": "1.0.0",
  "stylesheets": [
    {
      "title": "Mapbox Style",
      "version": "8",
      "specification": "https://docs.mapbox.com/mapbox-gl-js/style-spec/",
      "native": true,
      "tilingScheme": "GoogleMapsCompatible",
      "link": {
        "href": "https://example.org/api/v1/styles/night?f=mapbox",
        "rel": "stylesheet",
        "type": "application/vnd.mapbox.style+json"
      }
    },
    {
      "title": "OGC SLD",
      "version": "1.0",
      "native": false,
      "link": {
        "href": "https://example.org/api/v1/styles/night?f=sld10",
        "rel": "stylesheet",
        "type": "application/vnd.ogc.sld+xml;version=1.0"
      }
    }
  ],
  "layers": [
    {
      "id": "VegetationSrf",
      "type": "polygon",
      "sampleData": {
        "href": "https://demo.ldproxy.net/daraa/collections/VegetationSrf/items?f=json&limit=100",
        "rel": "start",
        "type": "application/geo+json"
      },
      "attributes": {
        "F_CODE": {
          "type": "string"
        }
      }
    },
    {
      "id": "HydrographyCrv",
      "type": "line",
      "sampleData": {
        "href": "https://demo.ldproxy.net/daraa/collections/HydrographyCrv/items?f=json&limit=100",
        "rel": "start",
        "type": "application/geo+json"
      },
      "attributes": {
        "F_CODE": {
          "type": "string"
        }
      }
    }
  ],
  "links": [
    {
      "href": "https://example.org/api/v1/resources/night-thumbnail.png",
      "rel": "preview",
      "type": "image/png",
      "title": "thumbnail of the night style applied to OSM data from Daraa, Syria"
    }
  ]
}
----
=================

[[rc_manage-styles]]
=== Requirements Class "Manage styles"

include::requirements/requirements_class_manage-styles.adoc[]

This section defines requirements for the case when the resources that are created, replaced, updated and deleted are styles. The general rules for Create/Replace/Delete/Update operations are specified in <<OAFeat-4,OGC API - Common - Part 4: Create, Replace, Update and Delete; Requirements Classes "Create/Replace/Delete" and "Update">>. This section specifies how those requirements apply to the API building blocks for styles.

[[manage-styles_styles-endpoint]]
==== Resources endpoint

[[create_style]]
===== Create a new style

[[req_manage-styles_resources-endpoint]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-styles/resources-endpoint*
^|A |For styles, the resources endpoints to create a new style SHALL be URIs specified by the URI template `{baseResource}/styles`.
^|B |When a new style is created, a minimal style metadata resource SHALL be created at `{baseResource}/styles/{styleId}/metadata`.
|===

The style metadata will be incomplete and should be updated by the client to keep the style metadata consistent with the style definition.

[[example_style_location]]
.New style response
=================
The URI of the new style is `https://example.org/api/v1/styles/night`.

[source]
----
HTTP/1.1 201 Created
Date: Sun, 28 Jul 2019 12:32:34 GMT
Location: https://example.org/api/v1/styles/night
----
=================

[[rec_manage-styles_id-exists]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:per-id}* |*/rec/manage-styles/id-exists*
^|A |If the request to create a new style is syntactically valid, but the server assigns new identifiers based on information in the stylesheet and the server already has a style with the identifier stated in the stylesheet, a response with status code `409` SHOULD be returned.
|===

[[update_default_style]]
===== Update the default style

The PATCH operation on `{baseResource}/styles` updates the default style of the style collection.

[[req_manage-styles_default-style-update]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-styles/default-style-update*
^|Condition |Server implements <<OAFeat-4,OGC API - Features - Part 4: Create, Replace, Update and Delete, Requirements Class "Update">>
^|Condition |Server advertises support for media type `application/merge-patch+json` in the API definition for PATCH requests at `{baseResource}/styles`
^|A |The server SHALL process PATCH requests with a content type `application/merge-patch+json` to such a resource endpoint as specified by <<rfc7396,RFC 7396 (JSON Merge Patch)>>.
^|B |The content of the request SHALL be based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
properties:
  default:
    type: string
    nullable: true
----
|===

A value `null` will remove the `default` member, i.e., there is no default style in the style collection. A value that is a valid style identifier in the collection will set that style as the default style. Otherwise an error will be returned.

[[manage-styles_style-endpoint]]
==== Resource endpoints

[[req_manage-styles_resource_endpoint]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-styles/resource-endpoint*
^|A |For styles, the resource endpoints SHALL be URIs specified by the URI template `{baseResource}/styles/{styleId}`.
^|B |The parameter `styleId` SHALL be the `id` property of a style obtained by previously having queried the Styles resource (i.e., responses to GET requests to `{baseResource}/styles`).
^|C |Additional resource endpoints SHALL be URIs specified by the URI template `{baseResource}/styles/{styleId}/metadata` (style metadata).
|===

[[replace_style]]
==== Replace a style

#TODO: There are two options how to handle PUT on `{baseResource}/styles/{styleId}`, depending on whether the server supports automated derivation of stylesheets in other style encodings.# 

#1. The PUT request removes all existing stylesheets of the style. The submitted stylesheet is accepted as the new style definition. If the server supports automatic derivation of stylesheets in other style encodings, it will derive other stylesheets from the new style definition and add them to the style metadata.#

#2. The PUT request sets or replaces the current stylesheet for the media type specified in the `Content-Type` header, but leaves other stylesheets of the style untouched. That is, all stylesheets are managed separately by clients.#

#Do we want to support one or both of the options?#

The style metadata resource at `{baseResource}/styles/{styleId}/metadata` is not updated. If the changes affect the metadata, the style metadata needs to be updated to keep the style metadata consistent with the style definition.

[[delete_style]]
==== Delete a style

This operation deletes the style with the id `styleId`. If no such style exists, an error is returned.

Deleting a style also deletes the subordinate resources, i.e., the style metadata.

[[req_manage-styles_styles-delete]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-styles/styles-delete*
^|A |For requests to the style metadata (template `{baseResource}/styles/{styleId}/metadata`), the DELETE operation SHALL not be supported.
^|B |DELETE requests to a style (template `{baseResource}/styles/{styleId}`) SHALL delete the style metadata of that style, too.
|===

[[replace_style_metadata]]
==== Replace the metadata of a style

Servers can support the PUT operation on `{baseResource}/styles/{styleId}/metadata` to replace the metadata of the style with the id `styleId`. If no such style exists, an error is returned.

[[per_manage-styles_replace-style-md]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/per/manage-styles/replace-style-md*
^|A |The server MAY accept style metadata based on the schema <<req_core_style-md-success,requirement /req/core/style-md-success, item B>> in all encodings supported by the API.
^|B |The server MAY ignore parts of the submitted metadata, in particular information that is managed by the server.
|===

For example, links of the link relation types `self` and `alternate` or the `stylesheets` array are in general automatically set by the server.

[[update_style_metadata]]
==== Update the metadata of a style

The PATCH operation on `{baseResource}/styles/{styleId}/metadata` updates the metadata of the style with the id `styleId`. If no such style exists, an error is returned.

[[req_manage-styles_metadata-update]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-styles/metadata-update*
^|Condition |Server implements <<OAFeat-4,OGC API - Features - Part 4: Create, Replace, Update and Delete, Requirements Class "Update">>
^|Condition |Server advertises support for media type `application/merge-patch+json` in the API definition for PATCH requests at `{baseResource}/styles/{styleId}/metadata`
^|A |The server SHALL process PATCH requests with a content type `application/merge-patch+json` to such a resource endpoint as specified by <<rfc7396,RFC 7396 (JSON Merge Patch)>>.
^|B |The content of the request SHALL be based upon the OpenAPI 3.0 schema specified in <<req_core_style-md-success,requirement `/req/core/style-md-success`>>, but with all properties set to `nullable: true` (so that they can be deleted).
|===

[[rfc7396_quote]]
From the RFC 7396 (JSON Merge Patch) specification:

[quote]
____
A JSON merge patch document describes changes to be
made to a target JSON document using a syntax that
closely mimics the document being modified. Recipients
of a merge patch document determine the exact set of
changes being requested by comparing the content of
the provided patch against the current content of the
target document. If the provided merge patch contains
members that do not appear within the target, those
members are added. If the target does contain the
member, the value is replaced. Null values in the
merge patch are given special meaning to indicate
the removal of existing values in the target.
____

Some examples using JSON Merge Patch:

To add or update the point of contact, the access constraint and the revision date, just send:

[source,JSON]
----
{
  "pointOfContact": "Jane Doe",
  "accessConstraints": "restricted",
  "dates": {
    "revision": "2019-05-17T11:46:12Z"
  }
}
----

To remove the point of contact, the access constraint and the revision date, send:

[source,JSON]
----
{
  "pointOfContact": null,
  "accessConstraints": null,
  "dates": {
    "revision": null
  }
}
----

For arrays the complete array needs to be sent. To add a keyword to the example style metadata object, send:

[source,JSON]
----
{
  "keywords": [ "basemap", "TDS", "TDS 6.1", "OGC API", "new keyword" ]
}
----

To remove the "TDS" keyword, send:

[source,JSON]
----
{
  "keywords": [ "basemap", "TDS 6.1", "OGC API", "new keyword" ]
}
----

To remove the keywords, send:

[source,JSON]
----
{
  "keywords": null
}
----

The same applies to `stylesheets`, `layers` and `links`. To update these members, the complete new array value has to be sent.

[[rc_style-validation]]
=== Requirements Class "Validation of styles"

include::requirements/requirements_class_style-validation.adoc[]

[[style_validate]]
==== Validate a style

[[req_style-validation_input]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/style-validation/input*
^|A |The server SHALL support the `Prefer` header with the https://tools.ietf.org/html/rfc7240#section-4.4["handling=strict" and "handling=lenient" Preferences].
^|B |The server SHALL support a parameter with the name "dry-run" in POST requests to the path `{baseResource}/styles` and in PUT requests to the path `{baseResource}/styles/{styleId}` with the following schema:

[source,YAML]
----
name: validate
in: query
required: false
style: form
explode: false
schema:
  type: boolean
  default: false
----
|===

[[req_style-validation_output]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/style-validation/output*
^|A |If the `Prefer` header has been provided in the request with the "handling=strict" preference, the server SHALL validate the submitted stylesheet for conformance with the style encoding. If an error in the stylesheet is identified, a response with status code `400` SHALL be returned.
^|A |If the `dry-run` parameter has been provided in the request with the value 'true', the server SHALL execute the request except that no style SHALL be created or updated. If no error condition is identified a response with status code `204` SHALL be returned.
|===

If no parameter `dry-run` is provided or the parameter has the value 'false', the standard response for a Create or Replace operation is returned.

////
commented out for now

[[rc_resources]]
=== Requirements Class "Resources"

include::requirements/requirements_class_resources.adoc[]

[[get_resources]]
==== Fetch resources

A GET request returns a list of resources that are currently available. The resources can be referenced from stylesheets. Resources in the Styles API are symbols, sprites and thumbnails.

For each resource the id and a link to the resource is provided.

#TODO: OGC Testbed-15 required only support for a limited number of the resources. Therefore, the currently simple approach is sufficient, but in general the operation could support paging (using a parameter `limit` and links to the `next` page in responses).#

[[req_resources_resources-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/resources/resources-op*
^|A |The server SHALL support the HTTP GET operation at the path `/resources`.
|===

[[req_resources_resources-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/resources/resources-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL be based upon the following OpenAPI 3.0 schema:

[source,YAML]
----
type: object
required:
  - resources
properties:
  resources:
    type: array
    items:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        link:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/schemas/link'
----
^|C |The `resources` member SHALL include one item for each resource currently on the server.
^|D |The `id` member of each resource SHALL be unique.
^|E |Each resource SHALL have a link to the resource (link relation: `item`) with the `type` attribute stating the media type of the resource.
|===

[[example_resource]]
.JSON encoding of resources
=================
[source,JSON]
----
{
  "resources": [
    {
      "id": "sprite.json",
      "link": {
        "href": "https://example.com/api/v1/resources/sprite.json",
        "type": "application/json",
        "rel": "item"
      }
    },
    {
      "id": "sprite.png",
      "link": {
        "href": "https://example.com/api/v1/resources/sprite.png",
        "type": "image/png",
        "rel": "item"
      }
    },
    {
      "id": "sprite.@2x.png",
      "link": {
        "href": "https://example.com/api/v1/resources/sprite.@2x.png",
        "type": "image/png",
        "rel": "item"
      }
    },
    {
      "id": "building.svg",
      "link": {
        "href": "https://example.com/api/v1/resources/building.svg",
        "type": "image/svg+xml",
        "rel": "item"
      }
    }
  ]
}
----
=================

[[get_resource]]
==== Fetch resource

A GET request returns a single resource.

[[req_resources_resource-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/resources/resource-op*
^|A |The server SHALL support the HTTP GET operation at the path `/resources/{resourceId}` for each resource referenced from `/resources`.
|===

[[req_resources_resource-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/resources/resource-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `200`.
^|B |The content of that response SHALL conform to the media type stated in the `Content-Type` header.
|===

[[rc_manage-resources]]
=== Requirements Class "Manage resources"

include::requirements/requirements_class_manage-resources.adoc[]

[[update_resource]]
==== Create or replace a resource

This operation creates or replaces the resource with id `resourceId`.

[[req_manage-resources_update-resource-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-resources/update-resource-op*
^|A |The server SHALL support the HTTP PUT operation at path `/resources/{resourceId}`.
|===

[[req_manage-resources_update-resource-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-resources/update-resource-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `204`.
^|B |The resource SHALL be the content submitted in the request.
|===

[[delete_resource]]
==== Delete a resource

This operation deletes the resource with the id `resourceId`. If no such resource exists, an error is returned.

[[req_manage-resources_delete-resource-op]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-resources/delete-resource-op*
^|A |The server SHALL support the HTTP DELETE operation at the path `/resources/{resourceId}`.
|===

[[req_manage-resources_delete-resource-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-resources/delete-resource-success*
^|A |A successful execution of the operation SHALL be reported as a response with an HTTP status code `204`.
|===

[[req_manage-resources_delete-resource-error]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/manage-resources/delete-resource-error*
^|A |If the style does not exist, a response with status code `404` SHALL be returned.
|===
////

////
commented out, HTML is already a requirements class in Common Core

[[rc_html]]
=== Requirements Class "HTML"

include::requirements/requirements_class_html.adoc[]

[[req_html_get]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/html/get*
^|A |Every `200`-response of a GET operation of the server that supports the media type `application/json` SHALL support the media type `text/html`.
|===

That is, all resources are expected to have a HTML representation except the stylesheets and the resources (symbols, etc.).

[[req_html_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/html/content*
^|A |Every `200`-response of the server with the media type `text/html` SHALL be a link:https://www.w3.org/TR/html5/[HTML 5 document] that includes the following information in the HTML body:

* all information identified in the schemas of the link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#responseObject[Response Object] in the HTML `<body>`, and
* all links in HTML `<a>` elements in the HTML `<body>`.
|===
////

[[rc_sld-10]]
=== Requirements Class "OGC SLD 1.0"

include::requirements/requirements_class_sld-10.adoc[]

[[req_sld-10_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-10/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.sld+xml;version=1.0`.
|===

[[req_sld-10_valid]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-10/valid*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid OGC SLD 1.0 documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[sld10_content]]
==== Expected content in an SLD 1.0 document

[[req_sld10_root]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld10/root*
^|A |In accordance with the SLD 1.0 standard, the root element of every SLD 1.0 stylesheet SHALL be a `StyledLayerDescriptor` element.
|===

The content of a stylesheet document will typically depend on the `{baseResource}`:

[[req_sld10_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld10/content*
^|A |If `{baseResource}` is a Landing Page of an API that publishes a dataset (i.e., it includes a Collections resource at `/collections`), the document SHALL contain one or more `NamedLayer` elements with names corresponding to collection ids, each with at least one `UserStyle`.
^|B |If `{baseResource}` is a Collection, the document SHALL contain one `NamedLayer` element with the name corresponding to the collection id with at least one `UserStyle`.
^|C |If `{baseResource}` is a Landing Page of an API that publishes no dataset (i.e., it includes no Collections resource at `/collections`), the document SHALL contain one or more `NamedLayer` or `UserLayer` elements, each with at least one `UserStyle`.
|===

[[rec_sld10_style-names]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/sld10/style-names*
^|A |If a `UserStyle` has a name, it SHOULD correspond to the style id (but the name is not relevant for the processing of the style).
^|B |If a `UserStyle` has `FeatureTypeStyle` elements with a name, the name SHOULD correspond to the collection id.
^|C |If a `NamedLayer` has a `Name` and a `FeatureTypeStyle` with a `FeatureTypeName`, both SHOULD be consistent. 
|===

In the case of a `NamedLayer` with a `Name` and a `FeatureTypeStyle` with a `FeatureTypeName`, clients should be prepared to understand either of them, with the more specific `FeatureTypeName` taking priority (as in some cases the `Name` of the `NamedLayer` may refer to a particular symbolization, e.g. casing or center line).

If there are multiple `UserStyle` elements in a layer, clients should use the style with a name that matches the style id, if there is one. Otherwise they should pick any of the styles.

[[rc_sld-11]]
=== Requirements Class "OGC SLD 1.1"

include::requirements/requirements_class_sld-11.adoc[]

[[req_sld-11_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-11/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.ogc.sld+xml;version=1.1`.
|===

[[req_sld-11_valid]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/sld-11/valid*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid OGC SLD 1.1 documents without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`

[[sld11_content]]
==== Expected content in an SLD 1.1 document

The same rules apply like for <<sld10_content,SLD 1.0 documents>>.

[[rc_mapbox-styles]]
=== Requirements Class "Mapbox Style"

include::requirements/requirements_class_mapbox-style.adoc[]

[[req_mapbox-styles_media-type]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/media-type*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL support the media type `application/vnd.mapbox.style+json`.
|===

[[req_mapbox-styles_content]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/mapbox-style/content*
^|A |Every POST or PUT operation of the server that accepts a stylesheet document as content SHALL accept valid Mapbox Style documents (version 8) without errors.
|===

The list of operations in a server implementing all conformance classes of this draft specification is:

* POST `{baseResource}/styles`
* PUT `{baseResource}/styles/{styleId}`
