= Quick Start Guide to link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard

== Introduction

The OGC API - Style standard defines the API building blocks for Web APIs to manage and fetch styles. Web APIs are software interfaces that use an architectural that is founded and webb technologies and a style is a set of instructiosn used by a rending engine to symbolize features and/or coverages. 

This guide is not intededed to be a replacement for the proposed link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard. Instead this guide is intended to focus on the API's capabilities in order to help user get started and to increase their understanding. Please refer to the link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard for additional detail. This guide will use the term "Styles API" to refer to a Web API tha has Implemented the OGC API - Style Standard.

== Use Case

The styles API is design to support three main use cases:

* In conjunction with the OGC API - Maps standard to fetch styles and render spatial data on the server.

* By Map clients to fetch styles and render spatial data on the client

* By Visual style editors that create, update and delete styles for datasets shared by other implementations of the OGC APIs

== Key Concepts

Their are three main concepts used in the Styles API:

* Style - The main resource used in the API

* Stylesheet -  The encoding used by the style resource, a single style can contain one of more stylesheets. Example of stylesheets are OGC SLD 1.0, Mapbox Style & ESRI Layer file

* Stlye Metadata - General descriptive information of a style which allows users to disccover and select esisitng styles. Metadata is optional in the standard.

== Resources / Operation

!===
|**Resource / Operation** | **Path**| **Purpose** 
|Base Resource | {baseResource} | This is the API resource that an style can be associated with, for example, a feature dataset, a feature collection, or a coverage. 
|Conformance Class| /conformance | List the requirements that the API adheres to. 
|Styles| {baseResource}/styles | This operation is used to, return a list of available styles, create a new style or validate an existing style.
|Style | {baseResource}/styles/{styleId} | This operation is used to return, replace or delete the stylesheet of a style resource
|Style metadata | {baseResource}/styles/{styleId}/metadata | This operation is used to return or replace the metadata information of a style.
!===

Examples of simple use case

Fetch Styles
HTTP GET operation at the path {baseResource}/styles




