= Quick Start Guide to link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard

== Introduction

The OGC API - Style standard defines the API building blocks for Web APIs to manage and fetch styles. Web APIs are software interfaces that use an architecture that is founded on webb technologies, a style is a set of instructions used by a rending engine to symbolize features and/or coverages. 

This guide is not intended to be a replacement for the proposed link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard. Instead this guide is intended to focus on the API's capabilities in order to increase a users understanding and to help then get started. Please refer to the link:http://docs.ogc.org/DRAFTS/20-009.html[OGC API - Styles] Standard for additional detail. This guide will use the term "Styles API" to refer to a Web API that has implemented the OGC API - Style Standard.

== Use Case

The styles API is designed to support three main use cases:

* In conjunction with the OGC API - Maps standard to fetch styles and render spatial data on the server

* By map clients to fetch styles and render spatial data on the client

* By visual style editors that create, update and delete styles for datasets shared by other implementations of the OGC APIs

== Key Concepts

Their are three main concepts used in the Styles API:

* Style - The main resource used in the API

* Stylesheet -  The encoding used by the style resource, a single style can contain one of more stylesheets. Example of stylesheets are OGC SLD 1.0, Mapbox Style & ESRI Layer file

* Stlye Metadata - General descriptive information of a style which allows users to discover and select existing styles. Metadata is optional in the standard.

== Resources / Operation

!===
|**Resource / Operation** | **Path**| **Purpose** 
|Base Resource | {baseResource} | This is an API resource that a style can be associated with, for example, a feature dataset, a feature collection, or a coverage 
|Conformance Class| /conformance | Lists the requirements that the API adheres to
|Styles| {baseResource}/styles | This operation is used to return a list of available styles, create a new style or validate an existing style
|Style | {baseResource}/styles/{styleId} | This operation is used to return, replace or delete the stylesheet of a style resource
|Style metadata | {baseResource}/styles/{styleId}/metadata | This operation is used to return or replace the metadata information of a style
!===

== Basic operation examples

=== Accessing a Style's list
Performing a **HTTP GET** operation on the path _{baseResource}/styles_ returns a list of styles for the _baseResource_ which follows the OpenAPI 3.0 schema specified in the http://docs.ogc.org/DRAFTS/20-009.html#get_styles[standard].

[[example_styles]]
.Returned list of styles in JSON
=================
[source,JSON]
----
{
  "styles": [
    {
      "id": "night",
      "title": "Topographic night style",
      "links": [
        {
          "href": "https://example.com/api/v1/styles/night?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/night?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/night/metadata?f=json",
          "type": "application/json",
          "rel": "describedby"
        }
      ]
    },
    {
      "id": "topographic",
      "title": "Regular topographic style",
      "links": [
        {
          "href": "https://example.com/api/v1/styles/topographic?f=mapbox",
          "type": "application/vnd.mapbox.style+json",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/topographic?f=sld10",
          "type": "application/vnd.ogc.sld+xml;version=1.0",
          "rel": "stylesheet"
        },
        {
          "href": "https://example.com/api/v1/styles/topographic/metadata?f=json",
          "type": "application/json",
          "rel": "describedby"
        }
      ]
    }
  ]
}
----
=================

=== Accessing a style's stylesheet

Performing a **HTTP GET** operation on the path _{baseResource}/styles/{styleId}_ will return the stylesheet of the _baseResource_. The format of the returned stylesheet will conform to the format specified in the **HTTP Content-Type header**

=== Accessing a style's metadata
Performing a **HTTP GET** operation on the path _{baseResource}/styles/{styleId}/metadata_ will return the style metadata information following the OpenAPI 3.0 schema specified in the http://docs.ogc.org/DRAFTS/20-009.html#get_style_metadata[standard].

[[example_style_metadata]]
.Returned style metadata in JSON
=================
[source,JSON]
----
{
  "id": "night",
  "title": "Topographic night style",
  "description": "This topographic basemap style is designed to be used in situations with low ambient light. The style supports datasets based on the TDS 6.1 specification.",
  "keywords": [
    "basemap",
    "TDS",
    "TDS 6.1",
    "OGC API"
  ],
  "pointOfContact": "John Doe",
  "accessConstraints": "unclassified",
  "dates": {
    "creation": "2019-01-01T10:05:00Z",
    "publication": "2019-01-01T11:05:00Z",
    "revision": "2019-02-01T11:05:00Z",
    "validTill": "2019-02-01T11:05:00Z",
    "receivedOn": "2019-02-01T11:05:00Z"
  },
  "scope": "style",
  "version": "1.0.0",
  "stylesheets": [
    {
      "title": "Mapbox Style",
      "version": "8",
      "specification": "https://docs.mapbox.com/mapbox-gl-js/style-spec/",
      "native": true,
      "tilingScheme": "GoogleMapsCompatible",
      "link": {
        "href": "https://example.org/api/v1/styles/night?f=mapbox",
        "rel": "stylesheet",
        "type": "application/vnd.mapbox.style+json"
      }
    },
    {
      "title": "OGC SLD",
      "version": "1.0",
      "native": false,
      "link": {
        "href": "https://example.org/api/v1/styles/night?f=sld10",
        "rel": "stylesheet",
        "type": "application/vnd.ogc.sld+xml;version=1.0"
      }
    }
  ],
  "layers": [
    {
      "id": "VegetationSrf",
      "type": "polygon",
      "sampleData": {
        "href": "https://demo.ldproxy.net/daraa/collections/VegetationSrf/items?f=json&limit=100",
        "rel": "start",
        "type": "application/geo+json"
      },
      "attributes": {
        "F_CODE": {
          "type": "string"
        }
      }
    },
    {
      "id": "HydrographyCrv",
      "type": "line",
      "sampleData": {
        "href": "https://demo.ldproxy.net/daraa/collections/HydrographyCrv/items?f=json&limit=100",
        "rel": "start",
        "type": "application/geo+json"
      },
      "attributes": {
        "F_CODE": {
          "type": "string"
        }
      }
    }
  ],
  "links": [
    {
      "href": "https://example.org/api/v1/resources/night-thumbnail.png",
      "rel": "preview",
      "type": "image/png",
      "title": "thumbnail of the night style applied to OSM data from Daraa, Syria"
    }
  ]
}
----
=================
